
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false
  config.vm.box_check_update = false 
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.3.31"
    node1.vm.hostname = "node1"
    node1.vm.provision :shell, path: "scripts/node1.sh", run: 'always'
  end  

  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.3.32"
    node2.vm.hostname = "node2"
    node2.vm.provision :shell, path: "scripts/node2.sh", run: 'always'
  end

end