Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vbguest.auto_update = false
  config.vm.box_check_update = false 
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "centos8" do |node1|
    node1.vm.network "private_network", ip: "192.168.3.33"
    node1.vm.hostname = "centos8"
    #node1.vm.provision :shell, path: "scripts/node1.sh", run: 'always'
  end
end